import React, { useEffect, useRef, useState } from 'react';
import { FileCard, Header, Closing, TextLink } from './ui';
import team from './photos/8-team.jpg';
import paddles from './photos/9-paddles.jpg';
import indoor from './photos/10-indoor.jpg';
import outdoor from './photos/11-outdoor.jpg';
import community from './photos/12-community.jpg';
import './style.css';
import logo from './photos/13-logo.png';
import {CourtScene} from './CourtScene';
const photos = [ {src:team,alt:'Husky players together at an outdoor pickleball tournament',label:'Purple on the road'}, {src:paddles,alt:'Two club players smiling with JOOLA paddles',label:'Game faces. Good company.'}, {src:indoor,alt:'Club members cheering beside an indoor pickleball court',label:'The sideline is part of the team'}, {src:outdoor,alt:'Players rallying on a tree-lined outdoor court',label:'A little fresh air, a lot of rallies'}, {src:community,alt:'Club members gathered together on a porch',label:'Off the court, still a team'} ];
const board=[['Presidents','Cosmo · Raine · Nick'],['Social media','Molly · Eric'],['Fundraising','Melody · Ada · Annabelle'],['External relations','Jayden'],['Open play coordinator','Spencer'],['General board members','Tati · Rohan']];
const instagram='https://www.instagram.com/huskypickleballclub/';
export function App(){
 const [menu,setMenu]=useState(false); const [selected,setSelected]=useState<number|null>(null); const [filter,setFilter]=useState('All'); const dialog=useRef<HTMLDialogElement>(null); const ball=useRef<HTMLDivElement>(null);
 useEffect(()=>{const nodes=document.querySelectorAll('.section,.sponsor');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in-view')}),{threshold:.08});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
 useEffect(()=>{if(selected!==null) dialog.current?.showModal(); else dialog.current?.close()},[selected]);
 const go=(e:React.MouseEvent<HTMLAnchorElement>,id:string)=>{e.preventDefault();setMenu(false);document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
 const visible=photos.map((p,i)=>({...p,i})).filter(p=>filter==='All'||(filter==='On court'?p.i<4:p.i===4));
 return <FileCard><div className="club">
 <nav className="nav" aria-label="Main navigation"><a className="brand" href="#home" onClick={e=>go(e,'home')}><img className="club-logo" src={logo} alt="Husky Pickleball Club logo"/><span>HUSKY<br/>PICKLEBALL CLUB</span></a><button className="menu" aria-expanded={menu} aria-controls="navlinks" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'} <span>☰</span></button><div id="navlinks" className={'navlinks '+(menu?'open':'')}>{[['Club','club'],['Play','play'],['Photos','photos'],['Board','board'],['Support','support']].map(([name,id])=><a key={id} href={'#'+id} onClick={e=>go(e,id)}>{name}</a>)}<a className="navcta" href={instagram} target="_blank" rel="noreferrer">Get in touch ↗</a></div></nav>
 <section id="home" className="hero"><div className="court-grid" aria-hidden="true"/><div className="hero-topline"><span>UNIVERSITY OF WASHINGTON</span><span>SEATTLE / ON & OFF THE COURT</span></div><div className="hero-type"><p className="eyebrow">THE GAME IS ONLY THE BEGINNING.</p><h1>Find your<br/><span>next rally.</span></h1></div><CourtScene/><div className="hero-bottom"><p>Find your people.<br/>Play your game.</p><div className="actions"><a className="btn gold" href="#play" onClick={e=>go(e,'play')}>Find your court <span>↗</span></a><a className="underlink" href="#club" onClick={e=>go(e,'club')}>Enter the club ↓</a></div><span className="scroll-note">SCROLL TO EXPLORE<br/>↓</span></div></section>
 <div className="ticker" aria-hidden="true"><span>PLAY HARD</span><b>✳</b><span>STAY SOCIAL</span><b>✳</b><span>GO DAWGS</span><b>✳</b><span>PLAY HARD</span></div>
 <section id="club" className="section intro"><div><p className="eyebrow">01 / THE CLUB</p><h2>Built for the game.<br/><em>Made for each other.</em></h2></div><div><p className="lead">We bring competition and a fun, social atmosphere together.</p><p>Our club connects pickleball lovers on and off the court, with a competitive travel team and a larger social team that comes together for monthly open plays. Whether you're chasing the next tournament or your next favorite rally, there's a place to connect.</p><div className="pillrow"><span>Competition</span><span>Community</span><span>Connection</span></div><div className="intro-photo"><img src={team} alt={photos[0].alt}/><span>ONE CLUB. EVERY KIND OF PLAYER.</span></div></div></section>
 <section id="play" className="section"><div className="sectionhead"><div><p className="eyebrow">02 / FIND YOUR COURT</p><h2>Two ways to play.<br/>One Husky community.</h2></div><span className="smallnote">Come for the game.<br/>Stay for the people.</span></div><div className="playgrid"><article className="playcard competitive"><img className="play-bg" src={indoor} alt=""/><span className="cardnumber">01</span><h3>The travel team</h3><p>For players ready to compete and represent UW on the collegiate stage.</p><div className="event"><span className="eyebrow">TRYOUTS · DRAFT DETAILS</span><strong>October 11</strong><span>IMA Gym B · 8-10 PM</span><small>Year to be confirmed.<br/>Public signup link coming soon.</small></div><a className="btn gold" href={instagram} target="_blank" rel="noreferrer">Ask about tryouts ↗</a></article><article className="playcard social"><img className="play-bg" src={outdoor} alt=""/><span className="cardnumber">02</span><h3>The social team</h3><p>Monthly open plays that bring our larger club community together. Good games, familiar faces, and room to connect.</p><div className="event"><span className="eyebrow">OPEN PLAY</span><strong>Next session?<br/>Stay in the loop.</strong><small>The open play schedule is on its way.<br/>Check Instagram for club updates.</small></div><a className="btn outline" href={instagram} target="_blank" rel="noreferrer">Follow club updates ↗</a></article></div></section>
 <section className="sponsor"><span className="eyebrow">THIS SEASON'S SPONSOR</span><div className="sponsorword">JOOLA<span> × HUSKY PICKLEBALL</span></div><p>Inclusion. Innovation. Inspiration.</p><p>Supported by the JOOLA Pickleball line, we're building an inclusive, welcoming community in the pickleball world.</p></section>
 <section id="photos" className="section"><div className="sectionhead"><div><p className="eyebrow">03 / CLUB LIFE</p><h2>This is our kind of court.</h2></div><div className="filters" aria-label="Photo categories">{['All','On court','Off court'].map(v=><button key={v} aria-pressed={filter===v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v}</button>)}</div></div><div className="gallery">{visible.map(p=><button key={p.i} className={'photocard photo-'+p.i} onClick={()=>setSelected(p.i)}><img src={p.src} alt={p.alt} loading="lazy"/><span>{p.label}<b>↗</b></span></button>)}</div><p className="photofoot">Photos from the club. Tap a photo for the full view.</p></section>
 <section id="board" className="section boardsection"><p className="eyebrow">04 / THE PEOPLE BEHIND THE PLAY</p><h2>Meet the board.</h2><div className="boardgrid">{board.map(([role,names])=><article key={role}><span>{role}</span><h3>{names}</h3></article>)}</div></section>
 <section id="support" className="section support"><div><p className="eyebrow">05 / BACK THE HUSKIES</p><h2>Help us take<br/>our game further.</h2><p>If you'd like to support the UW team's competition in the NCPA, you can find us on Venmo at <strong>@HuskyPickleball</strong>.</p><a className="btn purple" href="https://venmo.com/HuskyPickleball" target="_blank" rel="noreferrer">Support on Venmo ↗</a><small>Opens our Venmo profile. No payment is made here.</small></div><div className="resources"><h3>Follow the collegiate game.</h3><p>Tournaments, rankings, and the road to nationals.</p><TextLink href="https://ncpaofficial.com/">Explore the NCPA</TextLink><div className="contact"><h3>Let's talk pickleball.</h3><p>Questions about the club, tryouts, or supporting the team?</p><TextLink href={instagram}>@huskypickleballclub</TextLink></div></div></section>
 <footer className="clubfooter"><a className="brand" href="#home" onClick={e=>go(e,'home')}><img className="club-logo" src={logo} alt=""/>HUSKY PICKLEBALL CLUB ↗</a><span>University of Washington · Seattle</span><a href="#home" onClick={e=>go(e,'home')}>Back to top ↑</a></footer>
 <Closing>Redesign preview. Tryout details and signup link need confirmation; open play schedule will be added later. Front-end only.</Closing>
 <dialog ref={dialog} onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}><button className="closephoto" onClick={()=>setSelected(null)} aria-label="Close photo">Close ×</button>{selected!==null&&<><img src={photos[selected].src} alt={photos[selected].alt}/><p>{photos[selected].label}</p><div className="photoarrows"><button onClick={()=>setSelected((selected+4)%5)}>← Previous</button><button onClick={()=>setSelected((selected+1)%5)}>Next →</button></div></>}</dialog>
 </div></FileCard>;
}
