import React,{useEffect,useRef,useState} from 'react';
export function CourtScene(){
 const canvas=useRef<HTMLCanvasElement>(null),angle=useRef({x:-.23,y:-.35}),drag=useRef<{x:number,y:number}|null>(null),[motion,setMotion]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!media.matches);const fn=()=>setMotion(!media.matches);media.addEventListener('change',fn);return()=>media.removeEventListener('change',fn)},[]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;
 let frame=0,t=0,shown=true,last=0; const observer=new IntersectionObserver(([e])=>{shown=e.isIntersecting});observer.observe(el);
 const draw=(now=0)=>{frame=requestAnimationFrame(draw);if(!shown||now-last<32)return;last=now;t+=motion?.007:0;const rect=el.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio,1.5);if(el.width!==w*dpr||el.height!==h*dpr){el.width=w*dpr;el.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);
 const scroll=motion?Math.min(window.scrollY/Math.max(innerHeight,700),1):0;
 const scale=Math.min(w/660,h/510)*(1+scroll*.18),ax=angle.current.x+scroll*.23,ay=angle.current.y+(motion?Math.sin(t)*.13:0);
 const rot=([x,y,z]:number[])=>{const xx=x*Math.cos(ay)+z*Math.sin(ay),zz=-x*Math.sin(ay)+z*Math.cos(ay);return [xx,y*Math.cos(ax)-zz*Math.sin(ax),y*Math.sin(ax)+zz*Math.cos(ax)]};
 const project=(v:number[])=>{const [x,y,z]=rot(v),f=900/(900-z);return [w/2+x*scale*f,h*.49+y*scale*f,z]};
 // Court rings and a soft grounding shadow.
 ctx.save();ctx.translate(w/2,h*.83);ctx.scale(1,.24);ctx.strokeStyle='#a67af05c';ctx.lineWidth=1;for(let r=110;r<300;r+=60){ctx.beginPath();ctx.arc(0,0,r*scale,0,Math.PI*2);ctx.stroke()}const ground=ctx.createRadialGradient(0,0,0,0,0,260*scale);ground.addColorStop(0,'#b290df44');ground.addColorStop(1,'#b290df00');ctx.fillStyle=ground;ctx.fillRect(-300*scale,-300*scale,600*scale,600*scale);ctx.restore();
 // A solid paddle, built from projected front, back and side faces.
 const rawOutline=[[-105,-172],[-49,-188],[25,-176],[61,-140],[73,-67],[51,12],[14,46],[10,162],[-27,177],[-57,156],[-48,42],[-87,18],[-133,-55],[-137,-125]];
 const outline:number[][]=[];for(let i=0;i<rawOutline.length;i++){const p0=rawOutline[(i+rawOutline.length-1)%rawOutline.length],p1=rawOutline[i],p2=rawOutline[(i+1)%rawOutline.length],p3=rawOutline[(i+2)%rawOutline.length];for(let j=0;j<6;j++){const t=j/6;outline.push([0,1].map(k=>.5*((2*p1[k])+(-p0[k]+p2[k])*t+(2*p0[k]-5*p1[k]+4*p2[k]-p3[k])*t*t+(-p0[k]+3*p1[k]-3*p2[k]+p3[k])*t*t*t)))}}
 const transform=(x:number,y:number,z:number)=>[x*.94-37,y*.94+7,z-40];
 const front=outline.map(([x,y])=>project(transform(x,y,10))),back=outline.map(([x,y])=>project(transform(x,y,-14)));
 const path=(pts:number[][])=>{ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath()};
 path(back);ctx.fillStyle='#100b1e';ctx.fill();front.forEach((p,i)=>{const j=(i+1)%front.length;path([p,front[j],back[j],back[i]]);ctx.fillStyle='#806296';ctx.fill()});
 path(front);const face=ctx.createLinearGradient(w*.2,0,w*.7,h*.7);face.addColorStop(0,'#9273bc');face.addColorStop(.35,'#2f2144');face.addColorStop(1,'#0d0816');ctx.fillStyle=face;ctx.fill();ctx.strokeStyle='#cfb7f5';ctx.lineWidth=2;ctx.stroke();
 ctx.save();path(front);ctx.clip();ctx.strokeStyle='#bcb0d529';ctx.lineWidth=.6;for(let i=-200;i<300;i+=12){const a=project(transform(i,-200,11)),b=project(transform(i+140,190,11));ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()};ctx.restore();
 const label=project(transform(-41,-51,12));ctx.save();ctx.translate(label[0],label[1]);ctx.rotate(-.17+ay*.25);ctx.fillStyle='#f2e8ff';ctx.font=`900 ${33*scale}px Arial`;ctx.textAlign='center';ctx.fillText('HUSKY',0,0);ctx.font=`700 ${10*scale}px Arial`;ctx.letterSpacing='2px';ctx.fillText('PICKLEBALL CLUB',0,19*scale);ctx.restore();
 const grip=project(transform(-29,115,14));ctx.save();ctx.translate(grip[0],grip[1]);ctx.rotate(-.14);ctx.strokeStyle='#ddd1ed88';ctx.lineWidth=2;for(let j=-30;j<36;j+=8){ctx.beginPath();ctx.moveTo(-13*scale,j*scale);ctx.lineTo(12*scale,(j+4)*scale);ctx.stroke()};ctx.restore();
 // Perforated sphere: each hole has a 3D surface normal, projected as an ellipse.
 const center=[132,6,104],cp=project(center),r=96*scale*(900/(900-cp[2]));ctx.save();ctx.shadowColor='#dac17f55';ctx.shadowBlur=35*scale;ctx.beginPath();ctx.arc(cp[0],cp[1],r,0,Math.PI*2);const gold=ctx.createRadialGradient(cp[0]-r*.42,cp[1]-r*.5,0,cp[0],cp[1],r);gold.addColorStop(0,'#fffbc0');gold.addColorStop(.5,'#edd67a');gold.addColorStop(.85,'#b89a35');gold.addColorStop(1,'#816819');ctx.fillStyle=gold;ctx.fill();ctx.restore();
 const holes:number[][]=[];for(let i=0;i<32;i++){const y=1-2*(i+.5)/32,rr=Math.sqrt(1-y*y),phi=i*2.399963+ay+t*.12;const v=rot([Math.cos(phi)*rr,y,Math.sin(phi)*rr]);if(v[2]>.06)holes.push(v)}holes.sort((a,b)=>a[2]-b[2]);
 for(const [x,y,z] of holes){const px=cp[0]+x*r*.95,py=cp[1]+y*r*.95,theta=Math.atan2(y,x);ctx.save();ctx.translate(px,py);ctx.rotate(theta);ctx.beginPath();ctx.ellipse(0,0,9*scale*Math.max(z,.15),10*scale,0,0,Math.PI*2);ctx.fillStyle='#554913';ctx.fill();ctx.strokeStyle='#fff2a855';ctx.lineWidth=1.5;ctx.stroke();ctx.restore()}
 };draw();return()=>{cancelAnimationFrame(frame);observer.disconnect()};},[motion]);
 return <div className="court-scene"><canvas ref={canvas} tabIndex={0} role="img" aria-label="Interactive three-dimensional pickleball and paddle. Drag to rotate, or use arrow keys." onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;angle.current.y+=(e.clientX-drag.current.x)*.009;angle.current.x=Math.max(-.8,Math.min(.8,angle.current.x+(e.clientY-drag.current.y)*.005));drag.current={x:e.clientX,y:e.clientY}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();angle.current.y+=e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0;angle.current.x+=e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0}}}/><div className="scene-controls"><span>↔ DRAG TO ROTATE</span><button onClick={()=>setMotion(!motion)}>{motion?'Pause motion':'Enable motion'}</button><button onClick={()=>{angle.current={x:-.23,y:-.35}}}>Reset view</button></div></div>
}
